### ISSUE TITLE
[Question] If set PSI's initial value to 0 or its ssim value will be better than frame's time?

### ISSUE THREAD

**Issue by MikeLien** [WPO-Foundation/visualmetrics#19]
Hi,

Recently I work on some performance measurement tasks and leverage your code for SI and PSI calculation on [Hasal project](https://github.com/Mozilla-TWQA/Hasal/blob/master/lib/common/imageTool.py).

But we got a little confused why the [PSI Initial Value](https://github.com/WPO-Foundation/visualmetrics/blob/master/visualmetrics.py#L1141) is first frame's time instead of 0 or its ssim value as SI do.

If there has any reason to use frame's time as its initial value?

**Comment by pmeenan** [comment]
Pinging @pahammad who handled the SSIM version of PSI.

**Comment by pahammad** [comment]
Visual completion % is what both SI and PSI are integrating. SI uses histogram difference to track the % progress of visual completion, while PSI uses SSIM difference to track visual completion % progress. In practice, to handle some corner cases, we assume the visual completion % to be zero before the first visual change occurs. This is true for both SI and PSI. If the visual completion % is zero, simply following the integral equation (for both SI and PSI), the integral upto first visual change is simply the time elapsed from beginning of the video until the first visual change (measured in milliseconds). The reason why the code for PSI looks that way is to align with the non-uniform sampling scheme used in VisualMetrics repository. It's not a bug, and the math works out if you write down the calculations frame by frame, while keeping in mind the expectation of zero visual completion before first visual change occurs. 

There's a somewhat related thread that goes into an alternative way of writing SI / PSI integrals by breaking them into two parts; it may give you better clarity as well. See: https://github.com/pmdartus/speedline/issues/28

**Comment by MikeLien** [comment]
Thanks for the explanation and now I know the reason.
But I still has some questions about this solution.
1. How do you define the start point of data, is the time stamp of test script start?
2. How do I indicate a PSI value is better or worse if I measure one website two times and get different time for firstPaint?

**Comment by pahammad** [comment]
The code for SI and PSI in VisualMetrics repository work with a video as input. The video is usually from a WPT test run. The start point of the data is the first frame of the video, as defined by WPT's testing & video capture mechanism. If you measure a website twice, you will have two video files; just pass these videos one after another into the PSI code and you will get the corresponding PSI values. Same method works for SI. It is very common for all web performance metrics to vary from one test run to another even when you are testing the same exact website - the variation can even be non-Gaussian. This variation is mostly due to channel variations between the origin location and the client (testing) device. Hope this helps.

**Comment by MikeLien** [comment]
That's really helpful to me, thanks for the introduction about calculation flow. Eventually I found our framework doesn't adjust time stamp and align the offset thus result in a greater variation of firstPaint.
